### ISSUE TITLE
Add support for two-factor authentication

### ISSUE THREAD

**Issue by ignacio-penas** [nuvla/python-library#37]
In the current state is not possible for a user to login with username/password with two factor authenticatioon enabled. 

Suggested solution:
 - Either raise an exception when this happens to notify the user
    - Then propose to either use keys or temporarly remove the two-factor authentication
 - Find a workaround via Nuvla

**Comment by 0xbase12** [comment]
IMHO: we should raise an exception in the python client to notify the user and suggest him to generate an api-key instead. Never remove of two factor because it's a security hole.

**Comment by ignacio-penas** [comment]
User/Password authentications are unsecure. Will probably have to be removed in future version of the library. 
Closing this issue
